[manifest]
version = "1.0.0"
priority = -2147483648

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["main.lua"]

[[patches]]
[patches.pattern]
target = "main.lua"
position = "before"
pattern = "function love.run()"
payload = '''
_JOKERPRONOUNS_MOD_DIR = "{{lovely_hack:patch_dir}}"
'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
position = "after"
pattern = "local badges = {}"
payload = '''
local pronouns = JOKERPRONOUNS.get_pronouns(card)
if pronouns then
	badges[#badges + 1] = create_badge(
		(pronouns.ref_table and pronouns.ref_table[pronouns.ref_value]) or localize(pronouns.key),
		pronouns.color, pronouns.text_color or G.C.WHITE, 1
	)
end
'''
times = 1
match_indent = true